name: Main

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["22"]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: "pnpm-lock.yaml"
      - run: pnpm install --frozen-lockfile
      - run: pnpm -r build
      - run: pnpm -r lint
      - run: pnpm -r type-check
      - run: pnpm -r test

  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["22"]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: "packages/picosearch/pnpm-lock.yaml"
      - run: pnpm install --frozen-lockfile
      - run: pnpm -r build
      - run: pnpm run benchmark
        working-directory: packages/picosearch
      - name: Cache benchmark data
        uses: actions/cache@v3
        with:
          path: packages/picosearch/benchmark/data
          key: ${{ runner.os }}-benchmark-${{ matrix.node-version }}-${{ hashFiles('packages/picosearch/benchmark/data/**') }}
          restore-keys: |
            ${{ runner.os }}-benchmark-${{ matrix.node-version }}-
            ${{ runner.os }}-benchmark-

  deploy-npm-registry:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test, benchmark]
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: 'Use Node.js 22'
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: "pnpm-lock.yaml"
      - run: pnpm install --frozen-lockfile
      - run: pnpm -r build
      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: pnpm -r publish --provenance --no-git-checks --access public
        env:
          NPM_CONFIG_PROVENANCE: true
