name: Main

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["22"]
        package: 
          - picosearch
          - language-english
          - language-german
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: "packages/${{ matrix.package }}/pnpm-lock.yaml"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint
        working-directory: packages/${{ matrix.package }}
      - run: pnpm run type-check
        working-directory: packages/${{ matrix.package }}
      - run: pnpm run test
        working-directory: packages/${{ matrix.package }}

  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["22"]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: "packages/picosearch/pnpm-lock.yaml"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run benchmark
        working-directory: packages/picosearch
      - name: Cache benchmark data
        uses: actions/cache@v3
        with:
          path: packages/picosearch/benchmark/data
          key: ${{ runner.os }}-benchmark-${{ matrix.node-version }}-${{ hashFiles('packages/picosearch/benchmark/data/**') }}
          restore-keys: |
            ${{ runner.os }}-benchmark-${{ matrix.node-version }}-
            ${{ runner.os }}-benchmark-
